### PR TITLE
Adds Natural Language Understanding and fix a few bugs in the process

### LINKED ISSUE #547: Generate javadoc only for src files not test.
As you can see here: http://watson-developer-cloud.github.io/java-sdk/docs/similarity-search/

We are generating JavaDoc to the unit and integration tests. We should exclude those classes.

### LINKED ISSUE #610: [All Services] IBM Java results in only the 3DES cipher suite being choosen
IBM Java (any version) has incompatibilities with the OkHttpClient that are documented [here](https://github.com/square/okhttp/issues/3173). It is possible OkHttpClient may resolve this issue soon as there is current activity on it.

This [issue](https://github.com/cloudant/java-cloudant/issues/215) proposes a solution that involves configuring OkHttpClient with a custom SSLContext but I believe would require reflection to only do this when IBM Java is in use (you would not want to interfere with defaults on other platforms/JDKs).

### PR DESCRIPTION
**Pull request by germanattanasio**
## Summary 

* Adds support for NLU thanks to @mkistler 
* Adds `android-utils` to `build.gradle`
* Adds `build.gradle` to the examples
* Only push javadoc for the src folder fixes #547 

I will merge and do a release after that I fix #610

### CODE REVIEW

File: discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/collection/field/FieldAdapterFactory.java [hunk 1]
```diff
@@ -48,7 +48,6 @@ public void write(JsonWriter out, Field value) throws IOException {
```
Comment (mkistler) [inline discovery/src/main/java/com/ibm/watson/developer_cloud/discovery/v1/model/collection/field/FieldAdapterFactory.java]: Should update the copyright date on this file.

File: examples/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/RecognizeUsingWebSocketsWithSpeakerLabelsExample.java [hunk 2]
```diff
@@ -35,7 +35,7 @@
```
Comment (mkistler) [inline examples/src/main/java/com/ibm/watson/developer_cloud/speech_to_text/v1/RecognizeUsingWebSocketsWithSpeakerLabelsExample.java]: Should update the copyright date on this file (and check others).

**Comment by blakesteve** [comment]
android and gradle changes look good 👍

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+ * ### Concepts Identify general concepts that are referenced or alluded to in your content. Concepts that are detected
+ * typically have an associated link to a DBpedia resource.
+ *
+ * ### Entities Detect important people, places, geopolitical entities and other types of entities in your content.
+ * Entity detection recognizes consecutive coreferences of each entity. For example, analysis of the following text
+ * would count "Barack Obama" and "He" as the same entity:
+ *
+ * "Barack Obama was the 44th President of the United States. He took office in January 2009."
+ *
+ * ### Keywords Determine the most important keywords in your content. Keyword phrases are organized by relevance in the
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java]: I think the text flow here is broken.  The `### Keywords` should be on it's own line since it is the header for the text that follows.  Likewise for the other headers in this block comment.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java [hunk 4]
```diff
@@ -0,0 +1,155 @@
...
+  /**
+   * Analyzes text, HTML, or a public webpage with one or more text analysis features.
+   *
+   * @param parameters: An object containing request parameters. The `features` object and one of the `text`, `html`, or
+   *        `url` attributes are required.
+   * @return the {@link AnalysisResults} with the response
+   */
+  public ServiceCall<AnalysisResults> analyze(AnalyzeOptions parameters) {
+    RequestBuilder builder = RequestBuilder.post("/v1/analyze");
+    builder.query("version", versionDate);
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/NaturalLanguageUnderstanding.java]: Should use `VERSION` here for consistency.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/AnalysisResults.java [hunk 5]
```diff
@@ -0,0 +1,343 @@
...
+  public void addsemanticRoles(SemanticRolesResult semanticRoles) {
+    this.semanticRoles.add(semanticRoles);
+  }
+
+  /**
+   * Gets the language.
+   *
+   * @return the language
+   */
+  public String getLanguage() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/AnalysisResults.java]: Method name for getters be `language` instead of `getLanguage`.  This comment applies to all getters in this file.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/Author.java [hunk 6]
```diff
@@ -0,0 +1,43 @@
...
+
+  /** Name of the author. */
+  private String name;
+
+  /**
+   * Gets the name.
+   *
+   * @return the name
+   */
+  public String getName() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/Author.java]: Getter name should be "author" rather than "getAuthor".

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/CategoriesResult.java [hunk 7]
```diff
@@ -0,0 +1,63 @@
...
+  private String label;
+  /** Confidence score for the category classification. Higher values indicate greater confidence. */
+  private Double score;
+
+  /**
+   * Gets the label.
+   *
+   * @return the label
+   */
+  public String getLabel() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/CategoriesResult.java]: Getter name should be "label" rather than "getLabel"; "score" rather than "getScore".

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/ConceptsOptions.java [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+ * specific language governing permissions and limitations under the License.
+ */
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+
+/**
+ * Whether or not to analyze content for general concepts that are referenced or alluded to.
+ */
+public class ConceptsOptions extends GenericModel {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/ConceptsOptions.java]: This class should have a builder.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/ConceptsOptions.java [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+
+  /** Maximum number of concepts to return. */
+  private Integer limit;
+
+  /**
+   * Gets the limit.
+   *
+   * @return the limit
+   */
+  public Integer getLimit() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/ConceptsOptions.java]: Getter name should be "limit" rather than "getLimit".

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/ConceptsResult.java [hunk 10]
```diff
@@ -0,0 +1,84 @@
...
+  private Double relevance;
+  @SerializedName("dbpedia_resource")
+  private String dbpediaResource;
+
+  /**
+   * Gets the text.
+   *
+   * @return the text
+   */
+  public String getText() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/ConceptsResult.java]: Getter methods should be "text", "relevance", rather than "getText", "getRelevance".

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionOptions.java [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import java.util.List;
+
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+
+/**
+ * Whether or not to return emotion analysis of the content.
+ */
+public class EmotionOptions extends GenericModel {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionOptions.java]: This class should have a builder.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionResult.java [hunk 12]
```diff
@@ -0,0 +1,76 @@
...
+  public void addtargets(TargetedEmotionResults targets) {
+    this.targets.add(targets);
+  }
+
+  /**
+   * Gets the document.
+   *
+   * @return the document
+   */
+  public DocumentEmotionResults getDocument() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionResult.java]: Getter methods should be "document", "targets" rather than "getDocument", "getTargets".

I'll stop commenting on this now.  It just needs to be changed throughout.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EntitiesOptions.java [hunk 13]
```diff
@@ -0,0 +1,103 @@
...
+ * specific language governing permissions and limitations under the License.
+ */
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+
+/**
+ * Whether or not to return important people, places, geopolitical, and other entities detected in the analyzed content.
+ */
+public class EntitiesOptions extends GenericModel {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EntitiesOptions.java]: This class should have a builder.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/KeywordsOptions.java [hunk 14]
```diff
@@ -0,0 +1,83 @@
...
+ * specific language governing permissions and limitations under the License.
+ */
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+
+/**
+ * An option indicating whether or not important keywords from the analyzed content should be returned.
+ */
+public class KeywordsOptions extends GenericModel {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/KeywordsOptions.java]: This class should have a builder.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/Model.java [hunk 15]
```diff
@@ -0,0 +1,105 @@
...
+/**
+ * .
+ */
+public class Model extends GenericModel {
+
+  /** Shows as available if the model is ready for use. */
+  private String status;
+  /** Unique model ID. */
+  @SerializedName("model_id")
+  private String modelID;
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/Model.java]: I think the convention in the Java SDK is to use "Id" rather than "ID" (this differs from Swift by the way).  So to adhere to that convention, this variable and its associated getters/setters should use "Id".

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionOptions.java [hunk 16]
```diff
@@ -0,0 +1,74 @@
...
+  public void addtargets(String targets) {
+    this.targets.add(targets);
+  }
+
+  /**
+   * Gets the document.
+   *
+   * @return the document
+   */
+  public Boolean isDocument() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionOptions.java]: Do we want the "is" prefix on this getter?  It seems to break the convention of just using the name for getters -- even for boolean values.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionOptions.java [hunk 17]
```diff
@@ -0,0 +1,74 @@
...
+  /**
+   * Gets the targets.
+   *
+   * @return the targets
+   */
+  public List<String> getTargets() {
+    return targets;
+  }
+
+  /**
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EmotionOptions.java]: I think we do not want setters in this class, right?

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EntitiesOptions.java [hunk 18]
```diff
@@ -0,0 +1,103 @@
...
+  public String getModel() {
+    return model;
+  }
+
+  /**
+   * Gets the sentiment.
+   *
+   * @return the sentiment
+   */
+  public Boolean isSentiment() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EntitiesOptions.java]: I think we don't want "is" in the getter name here.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EntitiesOptions.java [hunk 19]
```diff
@@ -0,0 +1,103 @@
...
+  /**
+   * Gets the emotion.
+   *
+   * @return the emotion
+   */
+  public Boolean isEmotion() {
+    return emotion;
+  }
+
+  /**
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/EntitiesOptions.java]: I think we do not want setters in this class.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/KeywordsOptions.java [hunk 20]
```diff
@@ -0,0 +1,83 @@
...
+  public Integer getLimit() {
+    return limit;
+  }
+
+  /**
+   * Gets the sentiment.
+   *
+   * @return the sentiment
+   */
+  public Boolean isSentiment() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/KeywordsOptions.java]: I don't think we want "is" in these getter names.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/KeywordsOptions.java [hunk 21]
```diff
@@ -0,0 +1,83 @@
...
+  /**
+   * Gets the emotion.
+   *
+   * @return the emotion
+   */
+  public Boolean isEmotion() {
+    return emotion;
+  }
+
+  /**
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/KeywordsOptions.java]: I don't think we want setters in this class.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/RelationsOptions.java [hunk 22]
```diff
@@ -0,0 +1,43 @@
...
+ * specific language governing permissions and limitations under the License.
+ */
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+
+/**
+ * An option specifying if the relationships found between entities in the analyzed content should be returned.
+ */
+public class RelationsOptions extends GenericModel {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/RelationsOptions.java]: This class should have a builder.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/RelationsOptions.java [hunk 23]
```diff
@@ -0,0 +1,43 @@
...
+  /**
+   * Gets the model.
+   *
+   * @return the model
+   */
+  public String getModel() {
+    return model;
+  }
+
+  /**
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/RelationsOptions.java]: I don't think we want setters in this class.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SemanticRolesOptions.java [hunk 24]
```diff
@@ -0,0 +1,83 @@
...
+ * specific language governing permissions and limitations under the License.
+ */
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+
+/**
+ * An option specifying whether or not to identify the subjects, actions, and verbs in the analyzed content.
+ */
+public class SemanticRolesOptions extends GenericModel {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SemanticRolesOptions.java]: I think we want a builder for this class.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SemanticRolesOptions.java [hunk 25]
```diff
@@ -0,0 +1,83 @@
...
+  public Integer getLimit() {
+    return limit;
+  }
+
+  /**
+   * Gets the keywords.
+   *
+   * @return the keywords
+   */
+  public Boolean isKeywords() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SemanticRolesOptions.java]: I don't think we want "is" in this getter name.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SemanticRolesOptions.java [hunk 26]
```diff
@@ -0,0 +1,83 @@
...
+  /**
+   * Gets the entities.
+   *
+   * @return the entities
+   */
+  public Boolean isEntities() {
+    return entities;
+  }
+
+  /**
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SemanticRolesOptions.java]: I don't think we want setters in this class.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SentimentOptions.java [hunk 27]
```diff
@@ -0,0 +1,74 @@
...
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import java.util.List;
+
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+
+/**
+ * An option specifying if sentiment of detected entities, keywords, or phrases should be returned.
+ */
+public class SentimentOptions extends GenericModel {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SentimentOptions.java]: I think we want a builder for this class.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SentimentOptions.java [hunk 28]
```diff
@@ -0,0 +1,74 @@
...
+  public void addtargets(String targets) {
+    this.targets.add(targets);
+  }
+
+  /**
+   * Gets the document.
+   *
+   * @return the document
+   */
+  public Boolean isDocument() {
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SentimentOptions.java]: I don't think we want "is" in the getter name here.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SentimentOptions.java [hunk 29]
```diff
@@ -0,0 +1,74 @@
...
+  /**
+   * Gets the targets.
+   *
+   * @return the targets
+   */
+  public List<String> getTargets() {
+    return targets;
+  }
+
+  /**
```
Comment (mkistler) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/SentimentOptions.java]: I don't think we want setters in this class.

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/AnalyzeOptions.java [hunk 30]
```diff
@@ -0,0 +1,294 @@
...
+package com.ibm.watson.developer_cloud.natural_language_understanding.v1.model;
+
+import com.google.gson.annotations.SerializedName;
+import com.ibm.watson.developer_cloud.service.model.GenericModel;
+import com.ibm.watson.developer_cloud.util.Validator;
+
+/**
+ * An object containing request parameters.
+ */
+public class AnalyzeOptions extends GenericModel {
```
Comment (germanattanasio) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/AnalyzeOptions.java]: I will

File: natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/AnalysisResults.java (hunk 5 above)
Comment (germanattanasio) [inline natural-language-understanding/src/main/java/com/ibm/watson/developer_cloud/natural_language_understanding/v1/model/AnalysisResults.java]: I think the responses can be plain POJO because we don't need them to follow the same pattern as the Request objects. Responses are not implementing the Builder pattern
