### PR TITLE
fix getconfig when the schema contains a json_normalizations

### LINKED ISSUE #517: [discovery] Rename 'json' to 'json_normalizations' in Configuration
### Description

Users are unable to create a configuration with json normalization operations because the serialized name is incorrect.

### Steps to reproduce

1. Create a configuration file with some json normalization, example:
    ```json
    {
      "name": "my_config",
      "conversions": {
        "json_normalizations": [
          {
            "operation": "copy",
            "source_field": "some_field",
            "destination_field": "other_field"
          }
        ]
    }
    ```
1. Read in the file with the SDK
    ```java
     Configuration config = GsonSingleton.getGson().fromJson(new FileReader("/path/to/config-file.json"), Configuration.class);
    ```
1. Attempt to create a configuration
    ```java
    Discovery discovery = new Discovery("2016-12-15");
    discovery.setEndpoint("https://gateway.watsonplatform.net/discovery/api");
    discovery.setUsernameAndPassword("my_username", "my_password");
    String environmentId = "my_environment_id";
    CreateConfigurationRequest.Builder createBuilder = new CreateConfigurationRequest.Builder(environmentId);
     createBuilder.configuration(config);
     CreateConfigurationResponse createResponse = discovery.createConfiguration(createBuilder.build()).execute();
    ```
1. Expected config is not returned on GET requests:
    ```java
    GetConfigurationRequest getRequest = new GetConfigurationRequest.Builder(environmentId).build();
    GetConfigurationResponse getResponse = discovery.getConfiguration(getRequest).execute();
    System.out.println(getResponse); //does not have expected config, should be same as above with 'conversions.json_normalizations' key
    ```

### Solution
- [ ] change the `@SerializedName` annotation to `json_normalizations` in `com.ibm.watson.developer_cloud.discovery.v1.model.configuration.Conversions`
- [ ] write a test with a sample configuration like above and a test document

### When reporting a bug, please be sure to include the following:

- [X] Start the title with the service name in brackets:  `[speech-to-text] websockets...`
- [X] Steps to reproduce
- [X] Expected behavior
- [X] Actual behavior
- [X] JDK version (1.8.0_71 IBM)
- [X] java-sdk version (3.5.3)

### PR DESCRIPTION
**Pull request by Mikemosca**
fix getconfig when the schema contains a json_normalizations

Close #517

### CODE REVIEW

File: discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java [hunk 1]
```diff
@@ -101,6 +101,7 @@
  */
 public class DiscoveryServiceIT extends WatsonServiceTest {
   private static final String DISCOVERY_TEST_CONFIG_FILE = "src/test/resources/discovery/test-config.json";
+  private static final String DISCOVERY1_TEST_CONFIG_FILE = "src/test/resources/discovery/issue517.json";
```
Comment (maniax89) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: this seems like it would get messy really fast :-P

File: discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java [hunk 2]
```diff
@@ -742,6 +743,25 @@ public void queryWithAggregationAverageIsSuccessful() throws InterruptedExceptio
...
+    Configuration configuration =  getTestConfiguration(DISCOVERY1_TEST_CONFIG_FILE);
+
+    configuration.setName(uniqueConfigName);
+    createBuilder.configuration(configuration);
+    CreateConfigurationResponse createResponse = createConfiguration(createBuilder.build());
+
+    GetConfigurationRequest getRequest =
+        new GetConfigurationRequest.Builder(environmentId, createResponse.getConfigurationId()).build();
+    GetConfigurationResponse getResponse = discovery.getConfiguration(getRequest).execute();
+    // System.out.println(getResponse);
```
Comment (maniax89) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: remove this

File: discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java (hunk 1 above)
Comment (Mikemosca) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: What do you suggest.?

File: discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java (hunk 2 above)
Comment (Mikemosca) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: remove the commented out print?

Comment (maniax89) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: correct

File: discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java (hunk 1 above)
Comment (maniax89) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: i would probably just update the test-config to have a `json_normalizations` attribute.

basically make a copy of this test:

```
@Test
   public void getConfigurationIsSuccessful() {
     CreateConfigurationResponse createResponse = createTestConfig();
 
     GetConfigurationRequest getRequest = new GetConfigurationRequest.Builder(environmentId,
         createResponse.getConfigurationId()).build();
     GetConfigurationResponse getResponse = discovery.getConfiguration(getRequest).execute();
 
     assertEquals(createResponse.getName(), getResponse.getName());
   }
```

and do the same validation you have now:

```
assertEquals(1, getResponse.getConversions().getJson().size());
```

maybe you could call it
```
public void getConfigurationHasJsonNormalization() { ... }
```

but if it is easier to manage using issue numbers instead of this then go for it

Comment (Mikemosca) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: ok, I think I will keep this one as is.

File: discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java (hunk 2 above)
Comment (Mikemosca) [inline discovery/src/test/java/com/ibm/watson/developer_cloud/discovery/v1/DiscoveryServiceIT.java]: Agreed...
